### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'simpleText')

### ISSUE THREAD

**Issue by xMiyuka** [distubejs/ytpl#3]
## Describe the bug

```
TypeError: Cannot read properties of undefined (reading 'simpleText')
    at module.exports (C:\Users\Kaden\Documents\GitHub\NyuBot\node_modules\@distube\ytpl\lib\main.js:103:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _DisTubeHandler.resolvePlaylist (C:\Users\Kaden\Documents\GitHub\NyuBot\node_modules\distube\dist\index.js:1336:20)
    at async _DisTube.play (C:\Users\Kaden\Documents\GitHub\NyuBot\node_modules\distube\dist\index.js:2879:14)
    at async Object.run (C:\Users\Kaden\Documents\GitHub\NyuBot\src\commands\slash\Music\play.js:58:17)
```

Playlist with all songs effected: [Click here](https://www.youtube.com/playlist?list=PLjQTyDBOvqNx-bQMJ_CmIjgxb_wQSAWwP)

## Debug File
[yz8huqbsw9-1703007309429.txt](https://github.com/distubejs/ytdl-core/files/13718683/yz8huqbsw9-1703007309429.txt)

## Environment

- @distube/ytdl-core version: 4.13.3
- Node.js version: 20.10.0
- Operating system: Windows 10 (dev) | Ubuntu 20.04.6 LTS

**Comment by skick1234** [comment]
And what's your ytpl version?

**Comment by xMiyuka** [comment]
Thing is, I don't have that particular thing listed in my package.json
Related packages:
    "@discordjs/opus": "^0.9.0",
    "@distube/spotify": "^1.5.1",
    "@distube/yt-dlp": "^1.1.3",
    "@distube/ytdl-core": "^4.13.3",
     "yt-search": "^2.10.4",
     "ytdl-core": "^4.11.5"

**Comment by skick1234** [comment]
1. The console message is post it to ytpl issue page.
2. Run `npm ls @distube/ytpl` to check its version

**Comment by xMiyuka** [comment]
Ah my bad. Here you go:
@distube/ytpl@1.2.1

**Comment by xMiyuka** [comment]
Not a problem. Only a very small select songs so it isn't a huge deal if it isn't able to be resolved. I just find it strange that I was once able to play these songs without issue. I can't seem to find the root cause of it myself, reinstalling things and such. In regards to my last issue, it's the same songs yes. I assumed it was related to Cookies, which it wasn't as I did disable cookies for testing the issue now and it results in the same. Since you said you were unable to replicate my issue, I assume that means you are able to play the above songs without issue. If there is any more information you would like me to send your way feel free to reply to this thread.

**Comment by skick1234** [comment]
Actually, it is not related to your first issue (instant disconnect). I misread your follow up sentence.

**Comment by xMiyuka** [comment]
I made a little gif of it with the error posted in my VSC terminal (Copy and pasted in a discord code block) which can be viewed [Here](https://scs.twilightgamez.net/g/LErCv.gif)

**Comment by skick1234** [comment]
> Playing the playlist itself, told me to upload the dump here for review. This issue happens WITH and WITHOUT cookies enabled, so those are not the root cause of it.

what is the error you got when play that playlist?

**Comment by xMiyuka** [comment]
`TypeError: Cannot read properties of undefined (reading 'simpleText')
    at module.exports (C:\Users\Kaden\Documents\GitHub\NyuBot\node_modules\@distube\ytpl\lib\main.js:103:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _DisTubeHandler.resolvePlaylist (C:\Users\Kaden\Documents\GitHub\NyuBot\node_modules\distube\dist\index.js:1336:20)
    at async _DisTube.play (C:\Users\Kaden\Documents\GitHub\NyuBot\node_modules\distube\dist\index.js:2879:14)
    at async Object.run (C:\Users\Kaden\Documents\GitHub\NyuBot\src\commands\slash\Music\play.js:58:17)`

**Comment by skick1234** [comment]
I edited your issue since this is ytpl issue.

But in your gif, I don't know why this playlist is being played after you play that video. Did you hard coded play this playlist?

**Comment by xMiyuka** [comment]
> I edited your issue since this is ytpl issue.
> 
> But in your gif, I don't know why this playlist is being played after you play that video. Did you hard coded play this playlist?

That gif is 1 song from the playlist. Its just showing that the song just DC's immediately after queuing. 
The playlist being played is the "simpletext" error with all of the songs that do the issue above this. I cant queue any of the songs in the playlist period without the issue above happening which is just joining the vc, immediately disconnecting, and posting the error that I posted in the codeblock via the .gif file

**Comment by skick1234** [comment]
Your gif is related to ytdl-core or distube issue. And the error stack is due to your code. The queue wont be created if there is an error throw, so queue is undefined.

Anyway, check the error thrown though `<DisTube>.play()` method and send it to distube issues.

**Comment by skick1234** [comment]
Im typing on my phone so it is kinda slow. I will investigate this issue when i get home.

**Comment by xMiyuka** [comment]
> Your gif is related to ytdl-core or distube issue. And the error stack is due to your code. The queue wont be created if there is an error throw, so queue is undefined. I'm able to play your playlist/video, you can simply check it with DisTube or DisTube Premium bot on my discord server.
> 
> Anyway, check the error thrown though `<DisTube>.play()` method and send it to distube issues.

Thing is, the play method doesn't return an error at all. So I can't send an issue there. I just get the bot joining the VC, it says it queues, then immediately leaves VC.

**Comment by skick1234** [comment]
I know, it is the same issue as your issue you posted. And ofc idk exactly why, but the faq mentioned it should be due to ffmpeg.

**Comment by xMiyuka** [comment]
Weird that it could be ffmpeg. I can try to reinstall it. I have it installed the way that you have it in your FAQ channel
