### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by maggiben** [distubejs/ytpl#4]
The original author of the ytpl library has decided to deprecate and no longer work on it, a suspicious message suggesting using the google api might give us a hint of what happened, my question is do you plan to keep updating the library and carry the torch of this great library ?

**Comment by skick1234** [comment]
This fork is currently undergoing maintenance solely for bug fixes, with no plans for further feature development, and will soon be marked for deprecation. However, this isn't the conclusion, a new package is in the works to supersede ytdl-core, ytsr, and ytpl.
